version: "3.8"

services:
  server:
    build: .
    container_name: node-server
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - CHOKIDAR_USEPOLLING=true 
    volumes:
      - .:/app
      - /app/node_modules


  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=mohdsaadshaikh
      - POSTGRES_PASSWORD=mohdsaadshaikh
      - POSTGRES_DB=lms
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis-server
    restart: always
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"

volumes:
  pgdata:
  redisdata:
